<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run()
    {
        $courses = [
            // -----------------------------------------------------------
            // COMPUTER SCIENCE (1–25)
            // -----------------------------------------------------------
            ['code' => 'CS101', 'name' => 'Introduction to Computer Science', 'units' => 3],
            ['code' => 'CS102', 'name' => 'Programming I: Python', 'units' => 4],
            ['code' => 'CS103', 'name' => 'Programming II: Object-Oriented Java', 'units' => 4],
            ['code' => 'CS104', 'name' => 'Discrete Structures', 'units' => 3],
            ['code' => 'CS201', 'name' => 'Data Structures & Algorithms', 'units' => 4],
            ['code' => 'CS202', 'name' => 'Computer Architecture', 'units' => 3],
            ['code' => 'CS203', 'name' => 'Operating Systems', 'units' => 3],
            ['code' => 'CS204', 'name' => 'Database Systems', 'units' => 3],
            ['code' => 'CS205', 'name' => 'Web Development Fundamentals', 'units' => 3],
            ['code' => 'CS206', 'name' => 'Mobile Application Development', 'units' => 3],
            ['code' => 'CS301', 'name' => 'Artificial Intelligence', 'units' => 3],
            ['code' => 'CS302', 'name' => 'Machine Learning', 'units' => 3],
            ['code' => 'CS303', 'name' => 'Computer Networks', 'units' => 3],
            ['code' => 'CS304', 'name' => 'Cybersecurity Fundamentals', 'units' => 3],
            ['code' => 'CS305', 'name' => 'Full Stack Development', 'units' => 4],
            ['code' => 'CS306', 'name' => 'Distributed Systems', 'units' => 3],
            ['code' => 'CS307', 'name' => 'Algorithms Analysis', 'units' => 3],
            ['code' => 'CS308', 'name' => 'Software Engineering', 'units' => 3],
            ['code' => 'CS401', 'name' => 'Deep Learning', 'units' => 3],
            ['code' => 'CS402', 'name' => 'Cloud Computing', 'units' => 3],
            ['code' => 'CS403', 'name' => 'Information Retrieval', 'units' => 3],
            ['code' => 'CS404', 'name' => 'Human-Computer Interaction', 'units' => 3],
            ['code' => 'CS405', 'name' => 'Compiler Design', 'units' => 3],
            ['code' => 'CS406', 'name' => 'Capstone Project', 'units' => 4],
            ['code' => 'CS407', 'name' => 'Blockchain Technologies', 'units' => 3],

            // -----------------------------------------------------------
            // MATHEMATICS (26–50)
            // -----------------------------------------------------------
            ['code' => 'MATH101', 'name' => 'College Algebra', 'units' => 3],
            ['code' => 'MATH102', 'name' => 'Trigonometry', 'units' => 3],
            ['code' => 'MATH103', 'name' => 'Pre-Calculus', 'units' => 3],
            ['code' => 'MATH201', 'name' => 'Calculus I', 'units' => 4],
            ['code' => 'MATH202', 'name' => 'Calculus II', 'units' => 4],
            ['code' => 'MATH203', 'name' => 'Calculus III', 'units' => 4],
            ['code' => 'MATH204', 'name' => 'Linear Algebra', 'units' => 3],
            ['code' => 'MATH205', 'name' => 'Differential Equations', 'units' => 3],
            ['code' => 'MATH301', 'name' => 'Probability Theory', 'units' => 3],
            ['code' => 'MATH302', 'name' => 'Statistical Methods', 'units' => 3],
            ['code' => 'MATH303', 'name' => 'Real Analysis', 'units' => 3],
            ['code' => 'MATH304', 'name' => 'Complex Analysis', 'units' => 3],
            ['code' => 'MATH305', 'name' => 'Numerical Methods', 'units' => 3],
            ['code' => 'MATH306', 'name' => 'Abstract Algebra', 'units' => 3],
            ['code' => 'MATH307', 'name' => 'Topology', 'units' => 3],
            ['code' => 'MATH308', 'name' => 'Mathematical Modeling', 'units' => 3],
            ['code' => 'MATH309', 'name' => 'Applied Linear Algebra', 'units' => 3],
            ['code' => 'MATH401', 'name' => 'Advanced Statistics', 'units' => 3],
            ['code' => 'MATH402', 'name' => 'Stochastic Processes', 'units' => 3],
            ['code' => 'MATH403', 'name' => 'Optimization Theory', 'units' => 3],
            ['code' => 'MATH404', 'name' => 'Graph Theory', 'units' => 3],
            ['code' => 'MATH405', 'name' => 'Number Theory', 'units' => 3],
            ['code' => 'MATH406', 'name' => 'Game Theory', 'units' => 3],
            ['code' => 'MATH407', 'name' => 'Advanced Differential Equations', 'units' => 3],
            ['code' => 'MATH408', 'name' => 'Capstone in Mathematics', 'units' => 4],

            // -----------------------------------------------------------
            // BUSINESS & ECONOMICS (51–80)
            // -----------------------------------------------------------
            ['code' => 'BUS101', 'name' => 'Introduction to Business', 'units' => 3],
            ['code' => 'BUS102', 'name' => 'Business Communications', 'units' => 3],
            ['code' => 'BUS201', 'name' => 'Marketing Principles', 'units' => 3],
            ['code' => 'BUS202', 'name' => 'Financial Accounting', 'units' => 3],
            ['code' => 'BUS203', 'name' => 'Managerial Accounting', 'units' => 3],
            ['code' => 'BUS204', 'name' => 'Microeconomics', 'units' => 3],
            ['code' => 'BUS205', 'name' => 'Macroeconomics', 'units' => 3],
            ['code' => 'BUS301', 'name' => 'Business Law', 'units' => 3],
            ['code' => 'BUS302', 'name' => 'Organizational Behavior', 'units' => 3],
            ['code' => 'BUS303', 'name' => 'Entrepreneurship', 'units' => 3],
            ['code' => 'BUS304', 'name' => 'Business Finance', 'units' => 3],
            ['code' => 'BUS305', 'name' => 'Operations Management', 'units' => 3],
            ['code' => 'BUS306', 'name' => 'Econometrics', 'units' => 3],
            ['code' => 'BUS307', 'name' => 'Corporate Strategy', 'units' => 3],
            ['code' => 'BUS308', 'name' => 'International Business', 'units' => 3],
            ['code' => 'BUS309', 'name' => 'Digital Marketing', 'units' => 3],
            ['code' => 'BUS401', 'name' => 'Strategic Management', 'units' => 3],
            ['code' => 'BUS402', 'name' => 'Investment Analysis', 'units' => 3],
            ['code' => 'BUS403', 'name' => 'Financial Markets', 'units' => 3],
            ['code' => 'BUS404', 'name' => 'Supply Chain Management', 'units' => 3],
            ['code' => 'BUS405', 'name' => 'Human Resources Management', 'units' => 3],
            ['code' => 'BUS406', 'name' => 'Business Analytics', 'units' => 3],
            ['code' => 'BUS407', 'name' => 'Project Management', 'units' => 3],
            ['code' => 'BUS408', 'name' => 'Capstone in Business', 'units' => 4],
            ['code' => 'BUS409', 'name' => 'Behavioral Economics', 'units' => 3],
            ['code' => 'BUS410', 'name' => 'Leadership in Organizations', 'units' => 3],
            ['code' => 'BUS411', 'name' => 'Business Ethics', 'units' => 3],
            ['code' => 'BUS412', 'name' => 'Entrepreneurial Finance', 'units' => 3],
            ['code' => 'BUS413', 'name' => 'Pricing Strategy', 'units' => 3],
            ['code' => 'BUS414', 'name' => 'Brand Management', 'units' => 3],

            // -----------------------------------------------------------
            // BIOLOGY & LIFE SCIENCES (81–120)
            // -----------------------------------------------------------
            ['code' => 'BIO101', 'name' => 'General Biology I', 'units' => 4],
            ['code' => 'BIO102', 'name' => 'General Biology II', 'units' => 4],
            ['code' => 'BIO201', 'name' => 'Genetics', 'units' => 3],
            ['code' => 'BIO202', 'name' => 'Cell Biology', 'units' => 3],
            ['code' => 'BIO203', 'name' => 'Microbiology', 'units' => 3],
            ['code' => 'BIO204', 'name' => 'Ecology', 'units' => 3],
            ['code' => 'BIO205', 'name' => 'Evolutionary Biology', 'units' => 3],
            ['code' => 'BIO206', 'name' => 'Biostatistics', 'units' => 3],
            ['code' => 'BIO207', 'name' => 'Human Anatomy', 'units' => 3],
            ['code' => 'BIO208', 'name' => 'Human Physiology', 'units' => 3],
            ['code' => 'BIO301', 'name' => 'Molecular Biology', 'units' => 3],
            ['code' => 'BIO302', 'name' => 'Neurobiology', 'units' => 3],
            ['code' => 'BIO303', 'name' => 'Immunology', 'units' => 3],
            ['code' => 'BIO304', 'name' => 'Developmental Biology', 'units' => 3],
            ['code' => 'BIO305', 'name' => 'Plant Biology', 'units' => 3],
            ['code' => 'BIO306', 'name' => 'Marine Biology', 'units' => 3],
            ['code' => 'BIO307', 'name' => 'Research Methods in Biology', 'units' => 3],
            ['code' => 'BIO308', 'name' => 'Biochemistry', 'units' => 3],
            ['code' => 'BIO309', 'name' => 'Advanced Genetics', 'units' => 3],
            ['code' => 'BIO401', 'name' => 'Cancer Biology', 'units' => 3],
            ['code' => 'BIO402', 'name' => 'Bioinformatics', 'units' => 3],
            ['code' => 'BIO403', 'name' => 'Environmental Biology', 'units' => 3],
            ['code' => 'BIO404', 'name' => 'Virology', 'units' => 3],
            ['code' => 'BIO405', 'name' => 'Advanced Cell Biology', 'units' => 3],
            ['code' => 'BIO406', 'name' => 'Capstone in Biology', 'units' => 4],
            ['code' => 'BIO407', 'name' => 'Evolution of Vertebrates', 'units' => 3],
            ['code' => 'BIO408', 'name' => 'Human Genetics', 'units' => 3],
            ['code' => 'BIO409', 'name' => 'Systems Biology', 'units' => 3],
            ['code' => 'BIO410', 'name' => 'Genomics', 'units' => 3],
            ['code' => 'BIO411', 'name' => 'Plant Physiology', 'units' => 3],
            ['code' => 'BIO412', 'name' => 'Neurogenetics', 'units' => 3],
            ['code' => 'BIO413', 'name' => 'Animal Behavior', 'units' => 3],
            ['code' => 'BIO414', 'name' => 'Biomaterials', 'units' => 3],
            ['code' => 'BIO415', 'name' => 'Environmental Toxicology', 'units' => 3],
            ['code' => 'BIO416', 'name' => 'Evolutionary Ecology', 'units' => 3],
            ['code' => 'BIO417', 'name' => 'Principles of Parasitology', 'units' => 3],
            ['code' => 'BIO418', 'name' => 'Applied Microbiology', 'units' => 3],
            ['code' => 'BIO419', 'name' => 'Advanced Physiology', 'units' => 3],
            ['code' => 'BIO420', 'name' => 'Biophysics', 'units' => 3],

            // -----------------------------------------------------------
            // ENGINEERING (121–160)
            // -----------------------------------------------------------
            ['code' => 'ENGR101', 'name' => 'Introduction to Engineering', 'units' => 3],
            ['code' => 'ENGR102', 'name' => 'Engineering Graphics', 'units' => 3],
            ['code' => 'ENGR201', 'name' => 'Statics', 'units' => 3],
            ['code' => 'ENGR202', 'name' => 'Dynamics', 'units' => 3],
            ['code' => 'ENGR203', 'name' => 'Thermodynamics', 'units' => 3],
            ['code' => 'ENGR204', 'name' => 'Fluid Mechanics', 'units' => 3],
            ['code' => 'ENGR205', 'name' => 'Electrical Circuits', 'units' => 3],
            ['code' => 'ENGR301', 'name' => 'Material Science', 'units' => 3],
            ['code' => 'ENGR302', 'name' => 'Control Systems', 'units' => 3],
            ['code' => 'ENGR303', 'name' => 'Manufacturing Processes', 'units' => 3],
            ['code' => 'ENGR304', 'name' => 'Mechanics of Materials', 'units' => 3],
            ['code' => 'ENGR305', 'name' => 'Heat Transfer', 'units' => 3],
            ['code' => 'ENGR306', 'name' => 'Renewable Energy Systems', 'units' => 3],
            ['code' => 'ENGR307', 'name' => 'Engineering Ethics', 'units' => 3],
            ['code' => 'ENGR308', 'name' => 'Robotics', 'units' => 3],
            ['code' => 'ENGR401', 'name' => 'Advanced Thermodynamics', 'units' => 3],
            ['code' => 'ENGR402', 'name' => 'Finite Element Analysis', 'units' => 3],
            ['code' => 'ENGR403', 'name' => 'Embedded Systems', 'units' => 3],
            ['code' => 'ENGR404', 'name' => 'Biomedical Engineering', 'units' => 3],
            ['code' => 'ENGR405', 'name' => 'Capstone Engineering Project', 'units' => 4],
            ['code' => 'ENGR406', 'name' => 'Industrial Automation', 'units' => 3],
            ['code' => 'ENGR407', 'name' => 'Introduction to Mechatronics', 'units' => 3],
            ['code' => 'ENGR408', 'name' => 'Aerospace Propulsion', 'units' => 3],
            ['code' => 'ENGR409', 'name' => 'Structural Analysis', 'units' => 3],
            ['code' => 'ENGR410', 'name' => 'HVAC Engineering', 'units' => 3],
            ['code' => 'ENGR411', 'name' => 'Automotive Engineering', 'units' => 3],
            ['code' => 'ENGR412', 'name' => 'Photovoltaic Technology', 'units' => 3],
            ['code' => 'ENGR413', 'name' => 'Microelectromechanical Systems (MEMS)', 'units' => 3],
            ['code' => 'ENGR414', 'name' => 'Structural Dynamics', 'units' => 3],
            ['code' => 'ENGR415', 'name' => 'Environmental Engineering', 'units' => 3],
            ['code' => 'ENGR416', 'name' => 'Thermal Engineering', 'units' => 3],
            ['code' => 'ENGR417', 'name' => 'Aerospace Structures', 'units' => 3],
            ['code' => 'ENGR418', 'name' => 'Chemical Reaction Engineering', 'units' => 3],
            ['code' => 'ENGR419', 'name' => 'Geotechnical Engineering', 'units' => 3],
            ['code' => 'ENGR420', 'name' => 'Transportation Engineering', 'units' => 3],
            ['code' => 'ENGR421', 'name' => 'Machine Design', 'units' => 3],
            ['code' => 'ENGR422', 'name' => 'Nuclear Engineering Principles', 'units' => 3],
            ['code' => 'ENGR423', 'name' => 'Electrical Machines', 'units' => 3],
            ['code' => 'ENGR424', 'name' => 'Power Systems Engineering', 'units' => 3],

            // -----------------------------------------------------------
            // HUMANITIES & SOCIAL SCIENCES (161–200)
            // -----------------------------------------------------------
            ['code' => 'HIST101', 'name' => 'World History I', 'units' => 3],
            ['code' => 'HIST102', 'name' => 'World History II', 'units' => 3],
            ['code' => 'HIST201', 'name' => 'American History', 'units' => 3],
            ['code' => 'HIST202', 'name' => 'European Civilization', 'units' => 3],
            ['code' => 'PHIL101', 'name' => 'Introduction to Philosophy', 'units' => 3],
            ['code' => 'PHIL201', 'name' => 'Ethics', 'units' => 3],
            ['code' => 'PHIL202', 'name' => 'Logic', 'units' => 3],
            ['code' => 'PSY101', 'name' => 'General Psychology', 'units' => 3],
            ['code' => 'PSY201', 'name' => 'Developmental Psychology', 'units' => 3],
            ['code' => 'PSY202', 'name' => 'Cognitive Psychology', 'units' => 3],
            ['code' => 'PSY203', 'name' => 'Social Psychology', 'units' => 3],
            ['code' => 'SOC101', 'name' => 'Introduction to Sociology', 'units' => 3],
            ['code' => 'SOC201', 'name' => 'Cultural Anthropology', 'units' => 3],
            ['code' => 'SOC202', 'name' => 'Sociology of Education', 'units' => 3],
            ['code' => 'SOC203', 'name' => 'Urban Sociology', 'units' => 3],
            ['code' => 'ENG101', 'name' => 'English Composition I', 'units' => 3],
            ['code' => 'ENG102', 'name' => 'English Composition II', 'units' => 3],
            ['code' => 'ENG201', 'name' => 'American Literature', 'units' => 3],
            ['code' => 'ENG202', 'name' => 'World Literature', 'units' => 3],
            ['code' => 'ENG203', 'name' => 'Creative Writing', 'units' => 3],
            ['code' => 'LANG101', 'name' => 'Spanish I', 'units' => 3],
            ['code' => 'LANG102', 'name' => 'Spanish II', 'units' => 3],
            ['code' => 'LANG201', 'name' => 'French I', 'units' => 3],
            ['code' => 'LANG202', 'name' => 'French II', 'units' => 3],
            ['code' => 'LANG203', 'name' => 'German I', 'units' => 3],
            ['code' => 'LANG204', 'name' => 'German II', 'units' => 3],
            ['code' => 'ART101', 'name' => 'Art History', 'units' => 3],
            ['code' => 'ART102', 'name' => 'Drawing Fundamentals', 'units' => 3],
            ['code' => 'ART201', 'name' => 'Painting I', 'units' => 3],
            ['code' => 'ART202', 'name' => 'Digital Art & Design', 'units' => 3],
            ['code' => 'MUSIC101', 'name' => 'Music Appreciation', 'units' => 3],
            ['code' => 'MUSIC201', 'name' => 'Music Theory I', 'units' => 3],
            ['code' => 'THEA101', 'name' => 'Introduction to Theater', 'units' => 3],
            ['code' => 'THEA201', 'name' => 'Acting I', 'units' => 3],
            ['code' => 'THEA202', 'name' => 'Stage Production', 'units' => 3],
        ];

        DB::table('courses')->insert($courses);
    }
}
